name: flutter_cache_manager_hive
description: flutter_cache_manager implementation for hive.
version: 0.0.11
homepage: https://github.com/vishna/flutter_cache_manager_hive

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.0.1
  hive: ^2.0.2
  path_provider: "^2.0.0"
  uuid:  ^3.0.1
  http: "^0.13.1"
  path: "^1.6.4"
  pedantic: "^1.8.0+1"
  clock: ^1.0.1
  file: ^6.0.0-nullsafety.1
  rxdart: ^0.27.2
  meta: ^1.1.8
